### PR TITLE
Remove spaces from URL

### PR DESCRIPTION
**Pull request by jirijanata**
Remove spaces from URL, because VLC 3.0.4 is not able to handle the spaces.

### CODE REVIEW

**Comment by stefansundin** [comment]
Interesting. Thanks for taking the time to submit a fix. Is there an example stream on the internet somewhere that I can test with?

**Comment by jirijanata** [comment]
Dear Stefan, thank you very much for your quick response. I made a test page with two files (both are with space character)

https://jirijanata.github.io/text.html

If you try to open the file from Chrome, than it works. Otherwise not. I also [reported bug to VLC team](https://trac.videolan.org/vlc/ticket/21661), but it surely take some time..

Here I wrote more details:
https://github.com/stefansundin/vlc-protocol/issues/7

> Hello, I tried vlc-protocol and it works like a charm in Chrome. The problem is, that the URL with spaces is passed to VLC from Internet Explorer, Edge or Firefox. Chrome is changing spaces to %20.
> 
> VLC 3.0.4 can't handle network stream with spaces (quotes also doesn't help).

**Comment by stefansundin** [comment]
Great! I was able to reproduce it. I believe we need to make a similar change in all the other programs. I tested the exe and it had the same problem. I will try to test all of them over the next few days.

Thank you again.

**Comment by stefansundin** [comment]
I was able to update the exe with this change: https://github.com/stefansundin/vlc-protocol/commit/6fa2e1482e8ec539c62f00939258d1de66dfc108

I am wondering though, are there other characters that we should ensure are encoded as well?

**Comment by jirijanata** [comment]
I don't think so...I also tried some URL with special characters (letters with accents) and it works. So I think, that whitespace is the only one (which is also commonly used on the Internet).

`https://www.lepší.tv/web//folder/imgs/novinka_stanice_grafika_adventur.png`

**Comment by stefansundin** [comment]
I hadn't thought of testing images. :)

**Pull request merged**
